#include QMK_KEYBOARD_H


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_split_3x5_3(KC_Q, KC_W, KC_F, KC_P, KC_B, KC_J, KC_L, KC_U, KC_Y, KC_SCLN, KC_A, KC_R, KC_S, KC_T, KC_G, KC_M, KC_N, KC_E, KC_I, KC_O, LSFT_T(KC_Z), LCTL_T(KC_X), RALT_T(KC_C), KC_D, KC_V, KC_K, KC_H, RALT_T(KC_COMM), LCTL_T(KC_DOT), LSFT_T(KC_SLSH), TO(1), KC_BSPC, KC_TAB, KC_LGUI, KC_SPC, KC_ENT, KC_MPLY),
	[1] = LAYOUT_split_3x5_3(KC_TRNS, KC_7, KC_8, KC_9, KC_TRNS, KC_QUOT, KC_MINS, KC_EQL, KC_ASTR, KC_CIRC, KC_TRNS, KC_4, KC_5, KC_6, KC_0, KC_BSLS, KC_LPRN, KC_RPRN, KC_LBRC, KC_RBRC, KC_LSFT, KC_1, KC_2, KC_3, KC_TRNS, KC_PIPE, KC_GRV, KC_LALT, KC_LCTL, KC_RSFT, TO(2), KC_BSPC, KC_TAB, KC_DEL, TO(0), KC_ENT, KC_MPLY),
	[2] = LAYOUT_split_3x5_3(KC_TRNS, KC_TRNS, KC_PGUP, KC_TRNS, KC_TRNS, UC(0xE6), UC(0xF8), KC_TRNS, KC_TRNS, KC_TRNS, KC_LEFT, KC_UP, KC_DOWN, KC_RGHT, KC_TRNS, KC_TRNS, KC_LGUI, UC(0xE5), LCTL(KC_LALT), LCA(KC_LSFT), KC_TRNS, KC_HOME, KC_PGDN, KC_END, KC_TRNS, KC_TRNS, KC_RBRC, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TAB, KC_DEL, TO(0), KC_TRNS, KC_MPLY),
	[3] = LAYOUT_split_3x5_3(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RGB_HUI, RGB_SAI, RGB_VAI, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RGB_HUD, RGB_SAD, RGB_VAD, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LGUI, KC_SPC, KC_TRNS, KC_TRNS, KC_ENT, KC_RALT, KC_MPLY),
	[4] = LAYOUT_split_3x5_3(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
	[5] = LAYOUT_split_3x5_3(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
	[6] = LAYOUT_split_3x5_3(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
	[7] = LAYOUT_split_3x5_3(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
};


const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][2] = {
    [0] =   { ENCODER_CCW_CW(KC_MS_WH_UP, KC_MS_WH_DOWN)},
    [1] =   { ENCODER_CCW_CW(RGB_HUD, RGB_HUI)  },
    [2] =   { ENCODER_CCW_CW(RGB_VAD, RGB_VAI)  },
    [3] =   { ENCODER_CCW_CW(RGB_RMOD, RGB_MOD) },
    [4] =   { ENCODER_CCW_CW(KC_NO,KC_NO)  },
    [5] =   { ENCODER_CCW_CW(KC_NO,KC_NO)  },
    [6] =   { ENCODER_CCW_CW(KC_NO,KC_NO)  },
    [7] =   { ENCODER_CCW_CW(KC_NO,KC_NO)  }
    //                  Encoder 1                                     Encoder 2
};


